name: Test action

on:
  pull_request:
    branches:
      - '**'

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    environment: zerox-ci
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Run Zero-X Security Scan action
        uses: ./
        with:
          zerox-api-key: ${{ secrets.ZEROX_API_KEY }}
          zerox-url: ${{ secrets.ZEROX_URL }}
          # Optionally override scanners / metadata here if needed
          # scanners: 'vulns,iac,sast,malware,sbom'
